name: Build and Deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Get supported target version artifacts
        run: |
            bash get_artifacts.sh
            GITHASH=`git rev-parse --short HEAD`
            sed -i~ "s/@GITHASH@/$GITHASH/" src/App.vue
      - name: Build
        run: npm install && npm run build
      - name: Deploy to Cloudflare
        if: github.ref_name == 'master'
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
